apiVersion: v1
kind: Service
metadata:
  name: awesome-media-backend
spec:
  ports:
  - name: "http"
    port: 8090
    targetPort: 8090
  selector:
    app: awesome-media-backend
  type: NodePort
